# Generated by Django 4.2.4 on 2023-08-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('is_customer', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('address', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loyalty_Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('program_desc', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercoin.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supercoin.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='LP_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercoin.accounts')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercoin.loyalty_programs')),
            ],
        ),
    ]
