# Generated by Django 4.1.7 on 2023-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supercoin", "0002_loyalty_programs_date_loyalty_programs_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="amount",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactions",
            name="recipient",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
